### ISSUE TITLE
Failed to generate project Files

### ISSUE THREAD

**Issue by heitorboccato** [endink/Mediapipe4u-plugin#118]
### MediaPipe4U Version

20230829

### UE Version

5.0.x

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

After Clicking to generate the project files with Visual Studio i get the following Error:

ERROR: Expecting to find a type to be declared in a target rules named 'MediaPipe4U_DemoTarget'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool.

Here is the Log File that I get:
[UnrealVersionSelector-2023.09.29-15.38.22.log](https://github.com/endink/Mediapipe4u-plugin/files/12770466/UnrealVersionSelector-2023.09.29-15.38.22.log)

Log started at 29/09/2023 15:38:23 (2023-09-29T18:38:23Z)
No config file at C:\Users\Pichau\Documents\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml
Configuration will be read from:
  C:\Users\Pichau\AppData\Roaming\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml
Log file: C:\Users\Pichau\Desktop\DemoUE\MediaPipe4U-Demo\Saved\Logs\UnrealVersionSelector-2023.09.29-15.38.22.log

Note: Android toolchain NDK r21b recommended
Found Windows 10 SDK root at C:\Program Files\Windows Kits\10 (1)
Found Windows 10 SDK root at C:\Program Files (x86)\Windows Kits\10 (2)
Found Windows 10 SDK version 10.0.22621.0 at C:\Program Files (x86)\Windows Kits\10
Found Universal CRT version 10.0.22621.0 at C:\Program Files (x86)\Windows Kits\10
Win64 using Manual SDK 10.0.22621.0
Log file: C:\Users\Pichau\AppData\Local\UnrealBuildTool\Log_GPF.txt
Deleting old log file: C:\Users\Pichau\AppData\Local\UnrealBuildTool\Log_GPF-backup-2023.09.29-04.44.29.txt

---   SDK INFO START   ---

Some Platforms were skipped due to invalid SDK setup: IOS, Android, Linux, LinuxArm64.
See the log file for detailed information

---   SDK INFO END   ---

Discovering modules, targets and source code for project...
Found Visual Studio installation: C:\Program Files\Microsoft Visual Studio\2022\Community (Product=Microsoft.VisualStudio.Product.Community, Version=17.7.34031.279)
Skipping E:\UE_5.0\Engine\Intermediate\Build\BuildRules\UE5Rules.dll: File is installed
Skipping E:\UE_5.0\Engine\Intermediate\Build\BuildRules\UE5ProgramRules.dll: File is installed
Compiling C:\Users\Pichau\Desktop\DemoUE\MediaPipe4U-Demo\Intermediate\Build\BuildRules\MediaPipe4UDemoModuleRules.dll: Assembly does not exist
C:\Users\Pichau\Desktop\DemoUE\MediaPipe4U-Demo\Source\MediaPipe4U_Demo.Target.cs(11,3): error CS0103: The name 'IncludeOrderVersion' does not exist in the current context
C:\Users\Pichau\Desktop\DemoUE\MediaPipe4U-Demo\Source\MediaPipe4U_Demo.Target.cs(11,25): error CS0103: The name 'EngineIncludeOrderVersion' does not exist in the current context
C:\Users\Pichau\Desktop\DemoUE\MediaPipe4U-Demo\Source\MediaPipe4U_DemoEditor.Target.cs(12,3): error CS0103: The name 'IncludeOrderVersion' does not exist in the current context
C:\Users\Pichau\Desktop\DemoUE\MediaPipe4U-Demo\Source\MediaPipe4U_DemoEditor.Target.cs(12,25): error CS0103: The name 'EngineIncludeOrderVersion' does not exist in the current context
ERROR: Expecting to find a type to be declared in a target rules named 'MediaPipe4U_DemoTarget'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool.
BuildException: Expecting to find a type to be declared in a target rules named 'MediaPipe4U_DemoTarget'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool.
   at UnrealBuildTool.RulesAssembly.CreateTargetRulesInstance(String TypeName, TargetInfo TargetInfo) in d:\build\++UE5\Sync\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 532
   at UnrealBuildTool.RulesAssembly.CreateTargetRules(String TargetName, UnrealTargetPlatform Platform, UnrealTargetConfiguration Configuration, String Architecture, FileReference ProjectFile, CommandLineArguments Arguments) in d:\build\++UE5\Sync\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 723
   at UnrealBuildTool.ProjectFileGenerator.AddProjectsForAllTargets(PlatformProjectGeneratorCollection PlatformProjectGenerators, List`1 AllGames, List`1 AllTargetFiles, String[] Arguments, ProjectFile& EngineProject, List`1& GameProjects, Dictionary`2& ProgramProjects, Dictionary`2& RulesAssemblies) in d:\build\++UE5\Sync\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\ProjectFileGenerator.cs:line 2390
   at UnrealBuildTool.ProjectFileGenerator.GenerateProjectFiles(PlatformProjectGeneratorCollection PlatformProjectGenerators, String[] Arguments) in d:\build\++UE5\Sync\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\ProjectFileGenerator.cs:line 891
   at UnrealBuildTool.GenerateProjectFilesMode.Execute(CommandLineArguments Arguments) in d:\build\++UE5\Sync\Engine\Source\Programs\UnrealBuildTool\Modes\GenerateProjectFilesMode.cs:line 234
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in d:\build\++UE5\Sync\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 612
WriteFileIfChanged() wrote 0 changed files of 0 requested writes.
Timeline:

[ 0.000]
[ 0.000](+11.463) <unknown>
[11.463]

**Comment by endink** [comment]
Sorry , demo project is for unreal engine 5.1 , if you want to use UE5.0, you must switch version to 5.0, but i haven't test for it.
